package com.mb.domain;
// Generated 2016-8-14 9:29:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog", catalog = "mb")
public class Blog implements java.io.Serializable {

	private String mid;
	private User user;
	private String attitudesCount;
	private String bid;
	private String commentsCount;
	private String createdTime;
	private String repostsCount;
	private String weibotext;
	private String state;

	public Blog() {
	}

	public Blog(String mid) {
		this.mid = mid;
	}

	public Blog(String mid, User user, String attitudesCount, String bid, String commentsCount, String createdTime,
			String repostsCount, String weibotext, String state) {
		this.mid = mid;
		this.user = user;
		this.attitudesCount = attitudesCount;
		this.bid = bid;
		this.commentsCount = commentsCount;
		this.createdTime = createdTime;
		this.repostsCount = repostsCount;
		this.weibotext = weibotext;
		this.state = state;
	}

	@Id

	@Column(name = "mid", unique = true, nullable = false)
	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "attitudesCount")
	public String getAttitudesCount() {
		return this.attitudesCount;
	}

	public void setAttitudesCount(String attitudesCount) {
		this.attitudesCount = attitudesCount;
	}

	@Column(name = "bid")
	public String getBid() {
		return this.bid;
	}

	public void setBid(String bid) {
		this.bid = bid;
	}

	@Column(name = "commentsCount")
	public String getCommentsCount() {
		return this.commentsCount;
	}

	public void setCommentsCount(String commentsCount) {
		this.commentsCount = commentsCount;
	}

	@Column(name = "createdTime")
	public String getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(String createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "repostsCount")
	public String getRepostsCount() {
		return this.repostsCount;
	}

	public void setRepostsCount(String repostsCount) {
		this.repostsCount = repostsCount;
	}

	@Column(name = "weibotext")
	public String getWeibotext() {
		return this.weibotext;
	}

	public void setWeibotext(String weibotext) {
		this.weibotext = weibotext;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
