package com.mb.domain;
// Generated 2016-8-14 9:29:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commentrelation generated by hbm2java
 */
@Entity
@Table(name = "commentrelation", catalog = "mb")
public class Commentrelation implements java.io.Serializable {

	private String id;
	private String content;
	private String mid;
	private String uid;
	private String state;

	public Commentrelation() {
	}

	public Commentrelation(String id) {
		this.id = id;
	}

	public Commentrelation(String id, String content, String mid, String uid, String state) {
		this.id = id;
		this.content = content;
		this.mid = mid;
		this.uid = uid;
		this.state = state;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "mid")
	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	@Column(name = "uid")
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
