package com.mb.domain;
// Generated 2016-8-14 9:29:03 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Origindata generated by hbm2java
 */
@Entity
@Table(name = "origindata", catalog = "mb")
public class Origindata implements java.io.Serializable {

	private String mid;
	private Date postTime;
	private String uid;
	private String state;
	private String userState;

	public Origindata() {
	}

	public Origindata(String mid) {
		this.mid = mid;
	}

	public Origindata(String mid, Date postTime, String uid, String state, String userState) {
		this.mid = mid;
		this.postTime = postTime;
		this.uid = uid;
		this.state = state;
		this.userState = userState;
	}

	@Id

	@Column(name = "mid", unique = true, nullable = false)
	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "postTime", length = 19)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Column(name = "uid")
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "userState")
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

}
