package com.mb.domain;
// Generated 2016-8-14 9:29:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mb")
public class User implements java.io.Serializable {

	private String id;
	private int attnum;
	private int fansNum;
	private int mblogNum;
	private String mbrank;
	private String state;
	private String name;
	private Set<Blog> blogs = new HashSet<Blog>();

	public User() {
	}

	public User(String id, int attnum, int fansNum, int mblogNum) {
		this.id = id;
		this.attnum = attnum;
		this.fansNum = fansNum;
		this.mblogNum = mblogNum;
	}

	public User(String id, int attnum, int fansNum, int mblogNum, String mbrank, String name, Set blogs) {
		this.id = id;
		this.attnum = attnum;
		this.fansNum = fansNum;
		this.mblogNum = mblogNum;
		this.mbrank = mbrank;
		this.name = name;
		this.blogs = blogs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "attnum", nullable = false)
	public int getAttnum() {
		return this.attnum;
	}

	public void setAttnum(int attnum) {
		this.attnum = attnum;
	}

	@Column(name = "fansNum", nullable = false)
	public int getFansNum() {
		return this.fansNum;
	}

	public void setFansNum(int fansNum) {
		this.fansNum = fansNum;
	}

	@Column(name = "mblogNum", nullable = false)
	public int getMblogNum() {
		return this.mblogNum;
	}

	public void setMblogNum(int mblogNum) {
		this.mblogNum = mblogNum;
	}

	@Column(name = "mbrank")
	public String getMbrank() {
		return this.mbrank;
	}

	public void setMbrank(String mbrank) {
		this.mbrank = mbrank;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
