package com.mb.domain;
// Generated 2016-8-14 9:29:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mb")
public class User implements java.io.Serializable {

	private String id;
	private int attnum;
	private int fansNum;
	private int mblogNum;
	private int repost;
	private int comment;
	private int zanNum;
	private String mbrank;
	private String state;
	private String name;
	private String selfInf;
	private String Inf;
	private Set<Blog> blogs = new HashSet<Blog>();
	private Set<ResultMyPR> resultMyPRs=new HashSet<ResultMyPR>();
	private Set<ResultCenter> ResultCenter=new HashSet<ResultCenter>();
	private Set<ResultMax> ResultMax=new HashSet<ResultMax>();
	private Set<ResultPR> ResultPR=new HashSet<ResultPR>();
	private Set<ResultKS> ResultKS=new HashSet<ResultKS>();
	public User() {
	}

	public User(String id, int attnum, int fansNum, int mblogNum) {
		this.id = id;
		this.attnum = attnum;
		this.fansNum = fansNum;
		this.mblogNum = mblogNum;
	}

	public User(String id, int attnum, int fansNum, int mblogNum, String mbrank, String name, Set blogs) {
		this.id = id;
		this.attnum = attnum;
		this.fansNum = fansNum;
		this.mblogNum = mblogNum;
		this.mbrank = mbrank;
		this.name = name;
		this.blogs = blogs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "attnum", nullable = false)
	public int getAttnum() {
		return this.attnum;
	}

	public void setAttnum(int attnum) {
		this.attnum = attnum;
	}

	@Column(name = "fansNum", nullable = false)
	public int getFansNum() {
		return this.fansNum;
	}

	public void setFansNum(int fansNum) {
		this.fansNum = fansNum;
	}

	@Column(name = "mblogNum", nullable = false)
	public int getMblogNum() {
		return this.mblogNum;
	}

	public void setMblogNum(int mblogNum) {
		this.mblogNum = mblogNum;
	}

	@Column(name = "mbrank")
	public String getMbrank() {
		return this.mbrank;
	}

	public void setMbrank(String mbrank) {
		this.mbrank = mbrank;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResultMyPR> getResultMyPRs() {
		return resultMyPRs;
	}

	public void setResultMyPRs(Set<ResultMyPR> resultMyPRs) {
		this.resultMyPRs = resultMyPRs;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResultCenter> getResultCenter() {
		return ResultCenter;
	}

	public void setResultCenter(Set<ResultCenter> resultCenter) {
		ResultCenter = resultCenter;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResultMax> getResultMax() {
		return ResultMax;
	}

	public void setResultMax(Set<ResultMax> resultMax) {
		ResultMax = resultMax;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResultPR> getResultPR() {
		return ResultPR;
	}

	public void setResultPR(Set<ResultPR> resultPR) {
		ResultPR = resultPR;
	}

	public int getRepost() {
		return repost;
	}

	public void setRepost(int repost) {
		this.repost = repost;
	}

	public int getComment() {
		return comment;
	}

	public void setComment(int comment) {
		this.comment = comment;
	}

	public String getSelfInf() {
		return selfInf;
	}

	public void setSelfInf(String selfInf) {
		this.selfInf = selfInf;
	}

	public String getInf() {
		return Inf;
	}

	public void setInf(String inf) {
		Inf = inf;
	}

	public int getZanNum() {
		return zanNum;
	}

	public void setZanNum(int zanNum) {
		this.zanNum = zanNum;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResultKS> getResultKS() {
		return ResultKS;
	}

	public void setResultKS(Set<ResultKS> resultKS) {
		ResultKS = resultKS;
	}

}
